version: '3.8'

services:
  postgresql:
    image: 'postgres'
    environment:
      - POSTGRES_DB=trabalhobanco2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
  api:
    build: .
    ports:
      - 5000:5000
    environment:
      - HOST=postgresql
      - DATABASE=trabalhobanco2
    depends_on:
      - postgresql

volumes:
  dbdata: